/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Coding;

import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Nilusha De Silva
 */
public class MarkAttendance extends javax.swing.JFrame {

    /**
     * Creates new form MarkAttendance
     */
    private static Connection con;
    private static Statement stmt;
    private static ResultSet rs;
    private static ResultSet rs1;
    String uid = "u1";
    String sid, subid, sname, grade, subject, issue, exp, days, dte;
    int nod = 0;
    boolean a = false;

    public MarkAttendance() {
        initComponents();
    }

    public MarkAttendance(String uid) {
        initComponents();
        this.uid = uid;
        dbConnection();
        cmbsubjct.setEnabled(false);
        btncheck.setVisible(false);
    }

    public static void dbConnection() {
        try {
            con = ConnectionManager.getConnection();
            stmt = con.createStatement();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Connection Error!!" + e);
        }
    }

    public void setCombo() {
        String selsql = "Select Subject_ID from attendance where Card_ID ='" + txtcardid.getText() + "' AND MONTH(Card_IssueDate) =MONTH(CURRENT_DATE()) AND YEAR(Card_IssueDate) = YEAR(CURRENT_DATE()) ";
        try {
            rs = stmt.executeQuery(selsql);

            while (rs.next()) {
                cmbsubjct.addItem(rs.getString("Subject_ID"));
            }
            cmbsubjct.setEnabled(true);
            txtcardid.setEditable(false);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
            txtcardid.setEditable(true);

        }

    }

    public void checkExp() {
        LocalDate ld1 = LocalDate.parse(exp);

        Date d = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String current = sdf.format(d);
        LocalDate ld2 = LocalDate.parse(current);

        if (ld2.isBefore(ld1) || ld2.isEqual(ld1)) {
            a = true;
        } else {
            a = false;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtcardid = new javax.swing.JTextField();
        btncheck = new javax.swing.JButton();
        pnldetails = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtsid = new javax.swing.JTextField();
        txtsubid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtdays = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtissue = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtexpire = new javax.swing.JTextField();
        pnlid = new javax.swing.JPanel();
        lblphoto = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblsname = new javax.swing.JLabel();
        lblsubject = new javax.swing.JLabel();
        lblgrade = new javax.swing.JLabel();
        lblussue = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblexp = new javax.swing.JLabel();
        btnmark = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnback = new javax.swing.JButton();
        btnnew = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        cmbsubjct = new javax.swing.JComboBox<>();
        btncheckcard = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtgrade = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtsubname = new javax.swing.JTextField();
        txtlogid = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Mark Attendance");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel1.setText("Card ID          :");

        txtcardid.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtcardid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcardidActionPerformed(evt);
            }
        });
        txtcardid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcardidKeyPressed(evt);
            }
        });

        btncheck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Skip-forward-icon (1).png"))); // NOI18N
        btncheck.setBorderPainted(false);
        btncheck.setContentAreaFilled(false);
        btncheck.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncheckActionPerformed(evt);
            }
        });

        pnldetails.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel2.setText("Student ID             :");

        txtsid.setEditable(false);
        txtsid.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        txtsubid.setEditable(false);
        txtsubid.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel3.setText("Subject ID             :");

        txtdays.setEditable(false);
        txtdays.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtdays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdaysActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel4.setText("No of Days Attend :");

        txtissue.setEditable(false);
        txtissue.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel5.setText("Issue Date             :");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel6.setText("Expiry Date           :");

        txtexpire.setEditable(false);
        txtexpire.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        javax.swing.GroupLayout pnldetailsLayout = new javax.swing.GroupLayout(pnldetails);
        pnldetails.setLayout(pnldetailsLayout);
        pnldetailsLayout.setHorizontalGroup(
            pnldetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnldetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnldetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnldetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pnldetailsLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtsid))
                        .addGroup(pnldetailsLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtsubid, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnldetailsLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtdays, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnldetailsLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtissue, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnldetailsLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtexpire, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        pnldetailsLayout.setVerticalGroup(
            pnldetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnldetailsLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnldetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtsid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnldetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtsubid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnldetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtdays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnldetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtissue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnldetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtexpire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pnlid.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblphoto.setBackground(new java.awt.Color(255, 255, 255));
        lblphoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/admin-icon.png"))); // NOI18N
        pnlid.add(lblphoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 150, 150));

        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jLabel7.setText("St.Mary's Institution");
        pnlid.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 11, 180, 19));

        jLabel9.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jLabel9.setText("Ja-ela");
        pnlid.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        lblsname.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblsname.setText("Student Name");
        pnlid.add(lblsname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 220, -1));

        lblsubject.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblsubject.setText("Subect");
        pnlid.add(lblsubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 120, -1));

        lblgrade.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblgrade.setText("Grade");
        pnlid.add(lblgrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 120, -1));

        lblussue.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblussue.setText("2017/05/23");
        pnlid.add(lblussue, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 90, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel11.setText("to");
        pnlid.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 20, -1));

        lblexp.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblexp.setText("2017/6/23");
        pnlid.add(lblexp, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 90, -1));

        btnmark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cute-Ball-Go-icon.png"))); // NOI18N
        btnmark.setContentAreaFilled(false);
        btnmark.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmarkActionPerformed(evt);
            }
        });
        pnlid.add(btnmark, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 47, -1));

        btncancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cute-Ball-Stop-icon.png"))); // NOI18N
        btncancel.setContentAreaFilled(false);
        btncancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        pnlid.add(btncancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 47, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/vista_styled_hd_background_by_jcsawyer.jpg"))); // NOI18N
        jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnlid.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 280));

        btnback.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnback.setText("Back");
        btnback.setBorderPainted(false);
        btnback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        btnnew.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnnew.setText("New");
        btnnew.setBorderPainted(false);
        btnnew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel10.setText("Subject          :");

        cmbsubjct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        cmbsubjct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbsubjctActionPerformed(evt);
            }
        });

        btncheckcard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Skip-forward-icon (1).png"))); // NOI18N
        btncheckcard.setBorderPainted(false);
        btncheckcard.setContentAreaFilled(false);
        btncheckcard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncheckcard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncheckcardActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel12.setText("Grade :");

        txtgrade.setEditable(false);
        txtgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgradeActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel13.setText("Subject :");

        txtsubname.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnldetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(cmbsubjct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtgrade, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtsubname, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btncheck, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtcardid, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btncheckcard, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(18, 18, 18)
                .addComponent(pnlid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(btnnew, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnback)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtcardid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbsubjct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btncheckcard))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtgrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtsubname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(41, 41, 41))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btncheck)
                                .addGap(33, 33, 33)))
                        .addComponent(pnldetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnew)
                    .addComponent(btnback))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 85, -1, 490));

        txtlogid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtlogid.setText("U1");
        txtlogid.setNextFocusableComponent(txtcardid);
        getContentPane().add(txtlogid, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 40, 20));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/MTAyNHg3Njg,14811486_14707124.jpg"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btncheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncheckActionPerformed
        try {

            String check = "SELECT * FROM `attendance` where Card_ID = '" + txtcardid.getText() + "' AND Subject_ID='" + cmbsubjct.getSelectedItem().toString() + "'";
            rs = stmt.executeQuery(check);
            rs.next();
            sid = rs.getString(2);
            subid = rs.getString(3);
            days = Integer.toString(rs.getInt(4));
            issue = rs.getDate(5).toString();
            exp = rs.getDate(6).toString();

            pnlid.setVisible(true);

            String std = "Select Student_Name,Student_PhotoID from student where Student_ID='" + sid + "'";
            ResultSet rs1 = stmt.executeQuery(std);
            rs1.next();
            lblsname.setText(rs1.getString("Student_Name"));
            String path = rs1.getString("Student_PhotoID");

            String sub = "Select Subject_Name,Grade from subject where Subject_ID='" + subid + "'";
            ResultSet rs2 = stmt.executeQuery(sub);
            rs2.next();
            lblsubject.setText(rs2.getString("Subject_Name"));
            lblgrade.setText(rs2.getString("Grade"));

            lblussue.setText(issue);
            lblexp.setText(exp);

            File f = new File(path);

            lblphoto.setIcon(new ImageIcon(ImageIO.read(f)));
            txtcardid.setEditable(false);
            cmbsubjct.setEnabled(false);
            btncheckcard.setVisible(false);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Card_ID is Invalid!!!" + ex);
            cmbsubjct.setEnabled(true);
            btncheckcard.setVisible(true);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex);
            cmbsubjct.setEnabled(true);
            btncheckcard.setVisible(true);
        }
    }//GEN-LAST:event_btncheckActionPerformed

    private void txtdaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdaysActionPerformed

    private void btnmarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmarkActionPerformed
        try {
            checkExp();
            if (a == true) {
                nod = Integer.parseInt(days) + 1;
                days = Integer.toString(nod);
                String daily = "Insert into dailyattendance(Date,Student_ID,Subject_ID) values(?,?,?)";
                Date d = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String current = sdf.format(d);

                PreparedStatement pst1;
                pst1 = con.prepareStatement(daily);
                pst1.setString(1, current);
                pst1.setString(2, sid);
                pst1.setString(3, subid);
                pst1.executeUpdate();

                String newsql = "UPDATE `attendance` SET `NumberOfDaysAttend`=? WHERE Card_ID='" + txtcardid.getText() + "' AND Subject_ID='" + subid + "'  AND Student_ID='" + sid + "'";
                
                PreparedStatement pst;
                pst = con.prepareStatement(newsql);
                pst.setInt(1, nod);
                pst.executeUpdate();

                
                btnmark.setVisible(false);
                btncancel.setVisible(false);
                pnldetails.setVisible(true);
                txtsid.setText(sid);
                txtsubid.setText(subid);
                txtdays.setText(days);
                txtissue.setText(issue);
                txtexpire.setText(exp);
                txtcardid.setEditable(false);
                cmbsubjct.setEnabled(false);
                btncheckcard.setVisible(false);
                btncheck.setVisible(false);

            } else {
                JOptionPane.showMessageDialog(null, "Expired Card!!!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Already Marked!!");
        }
    }//GEN-LAST:event_btnmarkActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        this.setVisible(false);
        new Attendance(uid).setVisible(true);
    }//GEN-LAST:event_btnbackActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        txtlogid.setText(uid);
        pnlid.setVisible(false);
        pnldetails.setVisible(false);

    }//GEN-LAST:event_formWindowOpened

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        JOptionPane.showMessageDialog(null, "Attendance is not marked!!! Missused the Card!!!!!");
        btnmark.setVisible(false);
        btncancel.setVisible(false);
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewActionPerformed
        this.setVisible(false);
        new MarkAttendance(uid).setVisible(true);
    }//GEN-LAST:event_btnnewActionPerformed

    private void btncheckcardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncheckcardActionPerformed
        if (txtcardid.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please Enter Catd ID!!!!!");
        } else {
            setCombo();

        }

    }//GEN-LAST:event_btncheckcardActionPerformed

    private void txtgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgradeActionPerformed

    private void cmbsubjctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbsubjctActionPerformed
        String sbid = cmbsubjct.getSelectedItem().toString();
        String check = "Select Subject_Name,Grade from subject where Subject_ID=?";

        try {
            PreparedStatement pst;
            pst = con.prepareStatement(check);
            pst.setString(1, sbid);
            rs1 = pst.executeQuery();
            while (rs1.next()) {
                txtsubname.setText(rs1.getString("Subject_Name"));
                txtgrade.setText(rs1.getString("Grade"));
            }
            btncheck.setVisible(true);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Subject ID is Incorrect!!!");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);

        }
    }//GEN-LAST:event_cmbsubjctActionPerformed

    private void txtcardidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcardidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcardidActionPerformed

    private void txtcardidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcardidKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtcardid.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Please Enter Catd ID!!!!!");
            } else {
                setCombo();

            }
        }
    }//GEN-LAST:event_txtcardidKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MarkAttendance.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MarkAttendance.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MarkAttendance.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MarkAttendance.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MarkAttendance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btncheck;
    private javax.swing.JButton btncheckcard;
    private javax.swing.JButton btnmark;
    private javax.swing.JButton btnnew;
    private javax.swing.JComboBox<String> cmbsubjct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblexp;
    private javax.swing.JLabel lblgrade;
    private javax.swing.JLabel lblphoto;
    private javax.swing.JLabel lblsname;
    private javax.swing.JLabel lblsubject;
    private javax.swing.JLabel lblussue;
    private javax.swing.JPanel pnldetails;
    private javax.swing.JPanel pnlid;
    private javax.swing.JTextField txtcardid;
    private javax.swing.JTextField txtdays;
    private javax.swing.JTextField txtexpire;
    private javax.swing.JTextField txtgrade;
    private javax.swing.JTextField txtissue;
    private javax.swing.JLabel txtlogid;
    private javax.swing.JTextField txtsid;
    private javax.swing.JTextField txtsubid;
    private javax.swing.JTextField txtsubname;
    // End of variables declaration//GEN-END:variables
}
