/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Coding;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Nilusha De Silva
 */
public class NewCard extends javax.swing.JFrame {

    private static Connection con;
    private static Statement stmt;
    private static ResultSet rs;
    private static ResultSet rs1;
    String uid = "u1";
    String issue;
    String exp;

    public NewCard() {
        initComponents();
    }

    public NewCard(String uid) {
        initComponents();
        this.uid = uid;
        dbConnection();
        setCombo();
        Unable();
    }

    public static void dbConnection() {
        try {
            con = ConnectionManager.getConnection();
            stmt = con.createStatement();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Connection Error!!" + e);
        }
    }

    public void Enable() {
        txtsid.setEditable(true);
        cmbsubct.setEnabled(true);
        dateissue.setEnabled(true);
        dateexpire.setEnabled(true);

    }

    public void Unable() {
        txtsid.setEditable(false);
        cmbsubct.setEnabled(false);
        dateissue.setEnabled(false);
        dateexpire.setEnabled(false);

    }

    public void setCombo() {
        String selsql = "Select Subject_ID from subject";
        try {
            rs = stmt.executeQuery(selsql);

            while (rs.next()) {
                cmbsubct.addItem(rs.getString("Subject_ID"));
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtcardid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtsid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dateissue = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        dateexpire = new com.toedter.calendar.JDateChooser();
        txtname = new javax.swing.JTextField();
        btncheck = new javax.swing.JButton();
        btnmarksave = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        cmbsubct = new javax.swing.JComboBox<>();
        txtgrade = new javax.swing.JTextField();
        txtsubname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtlogid = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("New Card");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel1.setText("Card ID          :");

        txtcardid.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtcardid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcardidActionPerformed(evt);
            }
        });
        txtcardid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcardidKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel2.setText("Student ID     :");

        txtsid.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtsid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsidActionPerformed(evt);
            }
        });
        txtsid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsidKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel3.setText("Subject ID      :");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel5.setText("Issue Date      :");

        dateissue.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateissuePropertyChange(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel6.setText("Expire Date    :");

        dateexpire.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateexpirePropertyChange(evt);
            }
        });

        txtname.setEditable(false);
        txtname.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtnameMouseClicked(evt);
            }
        });

        btncheck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Skip-forward-icon (1).png"))); // NOI18N
        btncheck.setBorderPainted(false);
        btncheck.setContentAreaFilled(false);
        btncheck.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncheckActionPerformed(evt);
            }
        });

        btnmarksave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnmarksave.setText("Mark & Save");
        btnmarksave.setBorder(btnback.getBorder());
        btnmarksave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmarksave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmarksaveActionPerformed(evt);
            }
        });

        btnclear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnclear.setText("Clear");
        btnclear.setBorder(btnback.getBorder());
        btnclear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        btnback.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnback.setText("Back");
        btnback.setBorderPainted(false);
        btnback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        btnsave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsave.setText("Save");
        btnsave.setBorder(btnback.getBorder());
        btnsave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        cmbsubct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        cmbsubct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbsubctActionPerformed(evt);
            }
        });

        txtgrade.setEditable(false);
        txtgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgradeActionPerformed(evt);
            }
        });

        txtsubname.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel4.setText("Grade :");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel7.setText("Subject :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtcardid, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btncheck, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtsid, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(cmbsubct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel4)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtgrade, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtsubname, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(255, 255, 255))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnmarksave)
                                .addGap(18, 18, 18)
                                .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnback))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dateissue, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                    .addComponent(dateexpire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcardid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addComponent(btncheck, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbsubct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtgrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsubname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(dateissue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateexpire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnmarksave, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnclear)
                    .addComponent(btnback))
                .addGap(32, 32, 32))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 630, 300));

        txtlogid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtlogid.setText("U1");
        txtlogid.setNextFocusableComponent(txtcardid);
        getContentPane().add(txtlogid, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 40, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/MTAyNHg3Njg,14811486_14707124.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        txtcardid.setText("");
        txtsid.setText("");
        txtname.setText("");
        txtsubname.setText("");
        txtgrade.setText("");
        dateissue.setDate(null);
        dateexpire.setDate(null);
        Unable();
        txtcardid.setEditable(true);

    }//GEN-LAST:event_btnclearActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        this.setVisible(false);
        new Attendance(uid).setVisible(true);
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        try {
            if (txtcardid.getText().equals("") || txtsid.getText().equals("") || cmbsubct.getSelectedItem().toString().equals("") || dateissue.getDate().equals(null)
                    || dateexpire.getDate().equals(null)) {
                JOptionPane.showMessageDialog(null, "Add required Details!!");
            } else {
                LocalDate ld1 = LocalDate.parse(exp);
                LocalDate ld2 = LocalDate.parse(issue);

                if (ld2.isBefore(ld1) || ld2.isEqual(ld1)) {
                    String newsql = "insert into attendance (`Card_ID`, `Student_ID`, `Subject_ID`, `NumberOfDaysAttend`, `Card_IssueDate`, `Card_ExpiaryDate`)"
                            + " values(?,?,?,?,?,?)";
                    PreparedStatement pst;
                    pst = con.prepareStatement(newsql);

                    pst.setString(1, txtcardid.getText());
                    pst.setString(2, txtsid.getText());
                    pst.setString(3, cmbsubct.getSelectedItem().toString());
                    pst.setInt(4, 0);
                    pst.setString(5, issue);
                    pst.setString(6, exp);

                    pst.executeUpdate();
                    String newsql1 = "Update student "
                            + " SET Card_ID=? where Student_ID='" + txtsid.getText() + "'" ;
                    PreparedStatement pst2;
                    pst2 = con.prepareStatement(newsql1);
                    pst2.setString(1, txtcardid.getText());
                    pst2.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Successfully Added!!");

                } else {
                    JOptionPane.showMessageDialog(null, "Check the Dates Again!!!");
                    dateexpire.setDate(null);

                }

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Student already enroll for the subject!!! "+ex);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Acces Denied!!\nContact System Admin!!\n" + ex);
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btncheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncheckActionPerformed
        if (txtcardid.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please Enter Catd ID!!!!!");
        } else {
            try {
                String check = "SELECT `Card_ID`,`Student_ID` FROM `attendance` where Card_ID ='" + txtcardid.getText() + "'";
                rs = stmt.executeQuery(check);
                rs.next();
                if (rs.getString("Card_ID").equals(txtcardid.getText())) {

                    if (JOptionPane.showConfirmDialog(null, "Card_ID is existing!! Do you want to Add New Subject to this card??  ", "Warning!!",
                            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                        txtcardid.setEditable(false);
                        txtsid.setText(rs.getString("Student_ID"));

                    }

                } else {
                    txtcardid.setEditable(false);
                    txtsid.setEditable(true);

                }

            } catch (SQLException ex) {
                if (JOptionPane.showConfirmDialog(null, "Card_ID is Not Existing!! Do you want to Add New Card??  ", "Warning!!",
                        JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

                    txtcardid.setEditable(false);
                    txtsid.setEditable(true);
                }

            }
        }
    }//GEN-LAST:event_btncheckActionPerformed

    private void txtgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgradeActionPerformed

    private void dateissuePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateissuePropertyChange

        issue = String.format("%1$tY-%1$tm-%1$td", dateissue.getDate());
        if (issue.equals("")) {
            dateexpire.setEnabled(false);
        } else {
            dateexpire.setEnabled(true);
        }
    }//GEN-LAST:event_dateissuePropertyChange

    private void dateexpirePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateexpirePropertyChange

        exp = String.format("%1$tY-%1$tm-%1$td", dateexpire.getDate());


    }//GEN-LAST:event_dateexpirePropertyChange

    private void txtsidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsidKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                String check = "Select Student_Name from student where Student_ID='" + txtsid.getText() + "'";
                rs = stmt.executeQuery(check);
                rs.next();
                txtname.setText(rs.getString("Student_Name"));

                cmbsubct.setEnabled(true);

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Student ID is Incorrect!!!");
                txtsid.setText("");
                txtname.setText("");
            }
        }
    }//GEN-LAST:event_txtsidKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        txtlogid.setText(uid);

    }//GEN-LAST:event_formWindowOpened

    private void cmbsubctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbsubctActionPerformed
        String sbid = cmbsubct.getSelectedItem().toString();

        String check = "Select Subject_Name,Grade from subject where Subject_ID=?";

        try {
            PreparedStatement pst;
            pst = con.prepareStatement(check);
            pst.setString(1, sbid);
            rs1 = pst.executeQuery();
            while (rs1.next()) {
                txtsubname.setText(rs1.getString("Subject_Name"));
                txtgrade.setText(rs1.getString("Grade"));
            }

            dateissue.setEnabled(true);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Subject ID is Incorrect!!!");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);

        }
    }//GEN-LAST:event_cmbsubctActionPerformed

    private void txtsidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsidActionPerformed

    private void txtcardidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcardidKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtcardid.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Please Enter Catd ID!!!!!");
            } else {
                try {
                    String check = "SELECT `Card_ID`,`Student_ID` FROM `attendance` where Card_ID ='" + txtcardid.getText() + "'";
                    rs = stmt.executeQuery(check);
                    rs.next();
                    if (rs.getString("Card_ID").equals(txtcardid.getText())) {

                        if (JOptionPane.showConfirmDialog(null, "Card_ID is existing!! Do you want to Add New Subject to this card??  ", "Warning!!",
                                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                            txtcardid.setEditable(false);
                            txtsid.setText(rs.getString("Student_ID"));

                        }

                    } else {
                        txtcardid.setEditable(false);
                        txtsid.setEditable(true);

                    }

                } catch (SQLException ex) {
                    if (JOptionPane.showConfirmDialog(null, "Card_ID is Not Existing!! Do you want to Add New Card??  ", "Warning!!",
                            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

                        txtcardid.setEditable(false);
                        txtsid.setEditable(true);
                    }

                }
            }
    }//GEN-LAST:event_txtcardidKeyPressed
    }
    private void txtcardidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcardidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcardidActionPerformed

    private void txtnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnameMouseClicked
        try {
            String check = "Select Student_Name from student where Student_ID='" + txtsid.getText() + "'";
            rs = stmt.executeQuery(check);
            rs.next();
            txtname.setText(rs.getString("Student_Name"));

            cmbsubct.setEnabled(true);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Student ID is Incorrect!!!");
            txtsid.setText("");
            txtname.setText("");
        }
    }//GEN-LAST:event_txtnameMouseClicked

    private void btnmarksaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmarksaveActionPerformed
        try {
            if (txtcardid.getText().equals("") || txtsid.getText().equals("") || cmbsubct.getSelectedItem().toString().equals("") || dateissue.getDate().equals(null)
                    || dateexpire.getDate().equals(null)) {
                JOptionPane.showMessageDialog(null, "Add required Details!!");
            } else {
                LocalDate ld1 = LocalDate.parse(exp);
                LocalDate ld2 = LocalDate.parse(issue);

                if (ld2.isBefore(ld1) || ld2.isEqual(ld1)) {
                    String newsql = "insert into attendance (`Card_ID`, `Student_ID`, `Subject_ID`, `NumberOfDaysAttend`, `Card_IssueDate`, `Card_ExpiaryDate`)"
                            + " values(?,?,?,?,?,?)";
                    PreparedStatement pst;
                    pst = con.prepareStatement(newsql);

                    pst.setString(1, txtcardid.getText());
                    pst.setString(2, txtsid.getText());
                    pst.setString(3, cmbsubct.getSelectedItem().toString());
                    pst.setInt(4, 1);
                    pst.setString(5, issue);
                    pst.setString(6, exp);

                    pst.executeUpdate();
                    String daily = "Insert into dailyattendance(Date,Student_ID,Subject_ID) values(?,?,?)";

                    Date d = new Date();
                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                    String current = sdf.format(d);

                    PreparedStatement pst1;
                    pst1 = con.prepareStatement(daily);
                    pst1.setString(1, current);
                    pst1.setString(2, txtsid.getText());
                    pst1.setString(3, cmbsubct.getSelectedItem().toString());
                    pst1.executeUpdate();

                    String newsql1 = "Update student "
                    + " SET Card_ID=? where Student_ID='" + txtsid.getText() + "'" ;
                    PreparedStatement pst2;
                    pst2 = con.prepareStatement(newsql1);
                    pst2.setString(1, txtcardid.getText());
                    pst2.executeUpdate();
                   

                    JOptionPane.showMessageDialog(null, "Successfully Added!!");

                } else {
                    JOptionPane.showMessageDialog(null, "Check the Dates Again!!!");
                    dateexpire.setDate(null);

                }

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Student already enroll for the subject!!! "+ex);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Acces Denied!!\nContact System Admin!!\n" + ex);
        }
    }//GEN-LAST:event_btnmarksaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewCard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btncheck;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnmarksave;
    private javax.swing.JButton btnsave;
    private javax.swing.JComboBox<String> cmbsubct;
    private com.toedter.calendar.JDateChooser dateexpire;
    private com.toedter.calendar.JDateChooser dateissue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtcardid;
    private javax.swing.JTextField txtgrade;
    private javax.swing.JLabel txtlogid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtsid;
    private javax.swing.JTextField txtsubname;
    // End of variables declaration//GEN-END:variables
}
